### ISSUE TITLE
Do not give a default name to Exrethinkdb.Connection

### ISSUE THREAD

**Issue by josevalim** [hamiltop/exrethinkdb#28]
In actual code, it is very, very unlikely we want to use the default name because they will conflict. Imagine you are working on app A that has `worker(Exrethinkdb.Connection, [])` in its supervision tree. Then someone creates app B. Now, you want to run both as dependencies but they will conflict because they both use the same name for the connection.

I agree someone could just specify a name but, as things are currently designed, we are leading users to make this mistake.

I would make the name optional. If no name is given, it just returns the PID, and this is enough for the huge majority of cases. Otherwise you can pass the name explicitly as argument.

**Comment by hamiltop** [comment]
Default name isn't a requirement, but it does make life a lot easier.

`repl` mode for rethinkdb is not recommended in production solely because in most languages the connections are not threadsafe. Since we wrap the connection in a GenServer and support parallel queries via pipelining, sharing connections is not only possible but preferable. Using the default name is a great way to make that "just work".

I guess a pattern could be to wrap Connection (via `use Exrethinkdb.Connection`) in another module that exposes `run` and `start_link` and uses the default name of that module. Then register with the name of that Module. Then `MyApp.Connection` won't clash with `YourApp.Connection`.

Any other options I'm overlooking?

**Comment by josevalim** [comment]
@hamiltop if the preferable approach is to share a single connection then I would start the connection inside Exrethinkdb. It is pretty much what you are doing today except that the process is hosted inside Exrethinkdb.

This process can be configured via Mix config:

    config :exrethinkdb, :connection, host: "..."

Because configs are per project, there is no chance of conflict. Only the current project configuration is loaded.

**Comment by hamiltop** [comment]
I think multiple connections should be supported.

The `repl` concept is more a limitation of existing drivers (python and ruby). I don't think that concept should exist here.

I'm going to keep things simple. No default name for `Exrethinkdb.Connection`. I will however provide a `use Exrethinkdb.Connection` that can be included in another module and will define connect/run/next/etc. You can then provide a default name in that code at compile time. That will be unique per project (unless you have duplicate module names which is sort of out of our hands).

Re: `repl` mode. repl mode is a concept the python and ruby drivers present because of thread safety. javascript doesn't have it and we shouldn't have it. This is less of a convenience for hacking around in the repl and more a matter of a clean API.

I'll take a stab at it tonight. Thanks for chiming in! Your two cents are always appreciated.

**Comment by josevalim** [comment]
@hamiltop ah, to be clear, my last comment would still support multiple connections. `Exrethinkdb.Connection` would still exist, you would just support running one "instance" inside the `:exrethinkdb` app itself.

The main issue I see with the `use` approach is that it breaks if you are using something like poolboy. If you are using poolboy, you have no other option besides retrieving PIDs and sending the PIDs messages. In those cases, you won't work with a name.

I know you will likely support PIDs in `Exrethinkdb.Connection` anyway. My point is, if the recommended way of using Exrethinkdb is still behind a pool, then providing `use` won't help much. However, if you think one process per application is fine, then `use` sounds good enough.

**Comment by hamiltop** [comment]
I don't know yet. Pipelining in rethinkdb is new since 2.0 and none of the
official clients support it yet as far as I can tell.

I fully intend to support poolboy style connection pools and
Exrethinkdb.Connection will be as vanilla as possible, including the change
you suggest here.

In applications I'm working with, I find the single default connection
approach to be very simple and easy to use and I want to maintain that
experience. `use Exrethinkdb.Connection` seems like a great way to provide
that workflow without impeding on the flexibility of the normal Connection.

Time will tell which will be more useful, but I want to support both if
it's not too much trouble.

**Comment by hamiltop** [comment]
Updated as of 628c59173862486910664dbe5c8a85cc9e8eba9a

This is a very lightweight solution. The heavyweight solution is to do something like `ibrowse` where the application starts and it transparently manages a pool of connections to a given host/port. If a new host/port is needed, it creates a new pool.

That heavyweight solution is entirely compatible with the current codebase. If we decide a heavier solution is needed there's not much wasted code and effort.

Any issues you see with the latest code?

**Comment by josevalim** [comment]
This looks great!
