### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by hamiltop** [hamiltop/exrethinkdb#33]
Allow an asynchronous Task-based API.

```elixir
iex> result = Exrethinkdb.Connection.run(query, conn, async: true)
%Task{pid: #PID<0.60.0>, ref: #Reference<0.0.0.79>}
iex> Task.await(result)
%Exrethinkdb.Record{....}
```

Under the hood  in `run` we'd mimic `Task.async`:

```elixir
pid = get_pid(conn)
ref = Process.monitor pid
:ok = GenServer.call({:query, query, async: ref})
%Task{pid: pid, ref: ref}
```

And then in `Exrethinkdb.Connection` instead of `GenServer.reply` we would call `send pid, {ref, reply}`

Anyone see any issues here?

I remember discussing this with @josevalim a while back and wondering if maybe this is something that might be aided by potentially built-in functions in `Task`. While the code is easy to read and mimic, I worry about the implementation of Task changing under us. Alternatively I could just do:

```elixir
Task.async fn ->
 :ok = GenServer.call({:query, query})
end
```

And generate an additional process. As such, it might even be easier to not add this functionality in the first place and document the above as a suggested practice.

**Comment by josevalim** [comment]
@hamiltop it would be nice indeed if we could do async calls in GenServer. We will eventually implemented GenServer in Elixir and that would be easy.

There are no plans for changing Task messages in the short term. Maybe (really maybe) in Elixir 1.3.0, when we add routing, but that is still a long way to go. My only suggestion is to call the function `async/2` instead of changing the result of `run/2` based on an option.

Another option is to make them a stream (if you don't have one yet) and if it is supported by the adapter. So instead of doing the whole thing async, you could stream messages as they come.

**Comment by hamiltop** [comment]
The stream is somewhat of a different use case end-to-end. We can and do support async between the `Connection` and the server. We only support sync calls between client and `Connection` and that's what I wanted to explore.

Creating the extra process isn't that big of a deal and adding it to the client isn't really that useful when you can just call `Task.async` yourself.

This may be a good time resurrect work on `Streamz` (will want to get core functionality fully implemented in Exrethinkdb first though).

Thanks for chiming in! Going to close this.
